#!/bin/bash

function add_line_if_missing() {
    local -r line="$1"
    local -r file="$2"
    grep -q -F "${line}" "${file}" || echo "${line}" >> "${file}"
}

set -x
DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Tmux-related files
ln -n -s "${DIR}/tmux" "${HOME}/.tmux"
ln -s "${DIR}/tmux.conf" "${HOME}/.tmux.conf" 

# Git-Bash integration
ln -s "${DIR}/git/git-completion.bash" "${HOME}/.git-completion.bash"
ln -s "${DIR}/git/git-prompt.sh" "${HOME}/.git-prompt.sh"
ln -s "${DIR}/git/git-customizations.sh" "${HOME}/.git-customizations.sh"
add_line_if_missing "source ~/.git-customizations.sh" "${HOME}/.bashrc"

# Bash helpers
ln -s "${DIR}/bash/ssh-agent.sh" "${HOME}/.ssh-agent.sh"
add_line_if_missing "source ~/.ssh-agent.sh" "${HOME}/.bash_profile"

# Vim helpers
mkdir -p "${HOME}/.vim/autoload"
ln -s "${DIR}/vim/vim-pathogen/autoload/pathogen.vim" "${HOME}/.vim/autoload/pathogen.vim"
ln -n -s "${DIR}/vim/bundle" "${HOME}/.vim/bundle"
ln -s "${DIR}/vim/vimrc" "${HOME}/.vimrc"
ln -n -s "${DIR}/vim/vimfiles" "${HOME}/.vim/vimfiles"
