execute pathogen#infect()
syntax on
filetype plugin indent on

set background=dark
colorscheme solarized

" Make tab completion more sane when navigating files
set wildmode=longest,list,full
set wildmenu

" Disable folding in markdown plugin
let g:vim_markdown_folding_disabled = 1

" Tabs are useful; let F5 go back in tab, F6 go forward
nmap <F5> gT
nmap <F6> gt
